#!/bin/bash
cd "$(dirname "$0")"
find . -type f ! -name "README.md" ! -name "all_good_thing" -exec chmod u+x {} \;
git add . ':!README.md' ':!*/README.md'
git commit -m "add all good thing"
git push origin main
